# Generated by Django 3.1.2 on 2020-10-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nik', models.CharField(max_length=50)),
                ('no_peserta', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=50)),
            ],
        ),
    ]
