# Generated by Django 3.1.2 on 2020-10-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice1',
            new_name='choiceA',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice2',
            new_name='choiceB',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice3',
            new_name='choiceC',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice4',
            new_name='choiceD',
        ),
    ]
