# Generated by Django 3.1.2 on 2020-10-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0003_auto_20201012_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
    ]
