# Generated by Django 3.1.2 on 2020-10-13 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0004_person_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choiceE',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
