# Generated by Django 3.1.2 on 2020-10-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0005_question_choicee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(default='a/b/c/d/e', max_length=200),
        ),
    ]
