# Generated by Django 3.1.2 on 2020-10-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0006_auto_20201013_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subtest1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='subtest2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='subtest3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='subtest4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='subtest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(default='a/b/c/d/e', max_length=50),
        ),
    ]
